version: 2.1
# Only the npm install step is modified to use `npm install` instead of `npm ci`
jobs:
  build:
    docker:
      - image: cimg/node:18.20.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Install NPM packages
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}
      # ... (other steps remain unchanged)
workflows:
  version: 2
  build_and_test:
    jobs:
      - build